// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0--rc1
// source: pet-ms.proto

package pet_ms

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidGuardian  string                 `protobuf:"bytes,1,opt,name=uuid_guardian,json=uuidGuardian,proto3" json:"uuid_guardian,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BirthYear     uint64                 `protobuf:"varint,3,opt,name=birth_year,json=birthYear,proto3" json:"birth_year,omitempty"`
	Breed         string                 `protobuf:"bytes,4,opt,name=breed,proto3" json:"breed,omitempty"`
	Specie        uint64                 `protobuf:"varint,5,opt,name=specie,proto3" json:"specie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePetRequest) Reset() {
	*x = CreatePetRequest{}
	mi := &file_pet_ms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePetRequest) ProtoMessage() {}

func (x *CreatePetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_ms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePetRequest.ProtoReflect.Descriptor instead.
func (*CreatePetRequest) Descriptor() ([]byte, []int) {
	return file_pet_ms_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePetRequest) GetUuidGuardian() string {
	if x != nil {
		return x.UuidGuardian
	}
	return ""
}

func (x *CreatePetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePetRequest) GetBirthYear() uint64 {
	if x != nil {
		return x.BirthYear
	}
	return 0
}

func (x *CreatePetRequest) GetBreed() string {
	if x != nil {
		return x.Breed
	}
	return ""
}

func (x *CreatePetRequest) GetSpecie() uint64 {
	if x != nil {
		return x.Specie
	}
	return 0
}

type CreatePetResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NIdentification int64                  `protobuf:"varint,1,opt,name=n_identification,json=nIdentification,proto3" json:"n_identification,omitempty"`
	Uuid            string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UuidGuardian    string                 `protobuf:"bytes,3,opt,name=uuid_guardian,json=uuidGuardian,proto3" json:"uuid_guardian,omitempty"`
	Name            string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	BirthYear       uint64                 `protobuf:"varint,5,opt,name=birth_year,json=birthYear,proto3" json:"birth_year,omitempty"`
	Breed           string                 `protobuf:"bytes,6,opt,name=breed,proto3" json:"breed,omitempty"`
	Specie          string                 `protobuf:"bytes,7,opt,name=specie,proto3" json:"specie,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreatePetResponse) Reset() {
	*x = CreatePetResponse{}
	mi := &file_pet_ms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePetResponse) ProtoMessage() {}

func (x *CreatePetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pet_ms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePetResponse.ProtoReflect.Descriptor instead.
func (*CreatePetResponse) Descriptor() ([]byte, []int) {
	return file_pet_ms_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePetResponse) GetNIdentification() int64 {
	if x != nil {
		return x.NIdentification
	}
	return 0
}

func (x *CreatePetResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *CreatePetResponse) GetUuidGuardian() string {
	if x != nil {
		return x.UuidGuardian
	}
	return ""
}

func (x *CreatePetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePetResponse) GetBirthYear() uint64 {
	if x != nil {
		return x.BirthYear
	}
	return 0
}

func (x *CreatePetResponse) GetBreed() string {
	if x != nil {
		return x.Breed
	}
	return ""
}

func (x *CreatePetResponse) GetSpecie() string {
	if x != nil {
		return x.Specie
	}
	return ""
}

type UpdatePetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	BirthYear     uint64                 `protobuf:"varint,5,opt,name=birth_year,json=birthYear,proto3" json:"birth_year,omitempty"`
	Breed         string                 `protobuf:"bytes,6,opt,name=breed,proto3" json:"breed,omitempty"`
	Specie        uint64                 `protobuf:"varint,7,opt,name=specie,proto3" json:"specie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePetRequest) Reset() {
	*x = UpdatePetRequest{}
	mi := &file_pet_ms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePetRequest) ProtoMessage() {}

func (x *UpdatePetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_ms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePetRequest.ProtoReflect.Descriptor instead.
func (*UpdatePetRequest) Descriptor() ([]byte, []int) {
	return file_pet_ms_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePetRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdatePetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePetRequest) GetBirthYear() uint64 {
	if x != nil {
		return x.BirthYear
	}
	return 0
}

func (x *UpdatePetRequest) GetBreed() string {
	if x != nil {
		return x.Breed
	}
	return ""
}

func (x *UpdatePetRequest) GetSpecie() uint64 {
	if x != nil {
		return x.Specie
	}
	return 0
}

type UpdatePetResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NIdentification int64                  `protobuf:"varint,1,opt,name=n_identification,json=nIdentification,proto3" json:"n_identification,omitempty"`
	Uuid            string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UuidGuardian    string                 `protobuf:"bytes,3,opt,name=uuid_guardian,json=uuidGuardian,proto3" json:"uuid_guardian,omitempty"`
	Name            string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	BirthYear       uint64                 `protobuf:"varint,5,opt,name=birth_year,json=birthYear,proto3" json:"birth_year,omitempty"`
	Breed           string                 `protobuf:"bytes,6,opt,name=breed,proto3" json:"breed,omitempty"`
	Specie          string                 `protobuf:"bytes,7,opt,name=specie,proto3" json:"specie,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdatePetResponse) Reset() {
	*x = UpdatePetResponse{}
	mi := &file_pet_ms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePetResponse) ProtoMessage() {}

func (x *UpdatePetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pet_ms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePetResponse.ProtoReflect.Descriptor instead.
func (*UpdatePetResponse) Descriptor() ([]byte, []int) {
	return file_pet_ms_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePetResponse) GetNIdentification() int64 {
	if x != nil {
		return x.NIdentification
	}
	return 0
}

func (x *UpdatePetResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdatePetResponse) GetUuidGuardian() string {
	if x != nil {
		return x.UuidGuardian
	}
	return ""
}

func (x *UpdatePetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePetResponse) GetBirthYear() uint64 {
	if x != nil {
		return x.BirthYear
	}
	return 0
}

func (x *UpdatePetResponse) GetBreed() string {
	if x != nil {
		return x.Breed
	}
	return ""
}

func (x *UpdatePetResponse) GetSpecie() string {
	if x != nil {
		return x.Specie
	}
	return ""
}

type DeletePetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidGuardian  string                 `protobuf:"bytes,1,opt,name=uuid_guardian,json=uuidGuardian,proto3" json:"uuid_guardian,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePetRequest) Reset() {
	*x = DeletePetRequest{}
	mi := &file_pet_ms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePetRequest) ProtoMessage() {}

func (x *DeletePetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_ms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePetRequest.ProtoReflect.Descriptor instead.
func (*DeletePetRequest) Descriptor() ([]byte, []int) {
	return file_pet_ms_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePetRequest) GetUuidGuardian() string {
	if x != nil {
		return x.UuidGuardian
	}
	return ""
}

type DeletePetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePetResponse) Reset() {
	*x = DeletePetResponse{}
	mi := &file_pet_ms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePetResponse) ProtoMessage() {}

func (x *DeletePetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pet_ms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePetResponse.ProtoReflect.Descriptor instead.
func (*DeletePetResponse) Descriptor() ([]byte, []int) {
	return file_pet_ms_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPetRequest) Reset() {
	*x = GetPetRequest{}
	mi := &file_pet_ms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPetRequest) ProtoMessage() {}

func (x *GetPetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_ms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPetRequest.ProtoReflect.Descriptor instead.
func (*GetPetRequest) Descriptor() ([]byte, []int) {
	return file_pet_ms_proto_rawDescGZIP(), []int{6}
}

func (x *GetPetRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetPetResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NIdentification int64                  `protobuf:"varint,1,opt,name=n_identification,json=nIdentification,proto3" json:"n_identification,omitempty"`
	Uuid            string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UuidGuardian    string                 `protobuf:"bytes,3,opt,name=uuid_guardian,json=uuidGuardian,proto3" json:"uuid_guardian,omitempty"`
	Name            string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	BirthYear       uint64                 `protobuf:"varint,5,opt,name=birth_year,json=birthYear,proto3" json:"birth_year,omitempty"`
	Breed           string                 `protobuf:"bytes,6,opt,name=breed,proto3" json:"breed,omitempty"`
	Specie          string                 `protobuf:"bytes,7,opt,name=specie,proto3" json:"specie,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetPetResponse) Reset() {
	*x = GetPetResponse{}
	mi := &file_pet_ms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPetResponse) ProtoMessage() {}

func (x *GetPetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pet_ms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPetResponse.ProtoReflect.Descriptor instead.
func (*GetPetResponse) Descriptor() ([]byte, []int) {
	return file_pet_ms_proto_rawDescGZIP(), []int{7}
}

func (x *GetPetResponse) GetNIdentification() int64 {
	if x != nil {
		return x.NIdentification
	}
	return 0
}

func (x *GetPetResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetPetResponse) GetUuidGuardian() string {
	if x != nil {
		return x.UuidGuardian
	}
	return ""
}

func (x *GetPetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPetResponse) GetBirthYear() uint64 {
	if x != nil {
		return x.BirthYear
	}
	return 0
}

func (x *GetPetResponse) GetBreed() string {
	if x != nil {
		return x.Breed
	}
	return ""
}

func (x *GetPetResponse) GetSpecie() string {
	if x != nil {
		return x.Specie
	}
	return ""
}

var File_pet_ms_proto protoreflect.FileDescriptor

const file_pet_ms_proto_rawDesc = "" +
	"\n" +
	"\fpet-ms.proto\x12\x05proto\x1a\x1cgoogle/api/annotations.proto\"\x98\x01\n" +
	"\x10CreatePetRequest\x12#\n" +
	"\ruuid_guardian\x18\x01 \x01(\tR\fuuidGuardian\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"birth_year\x18\x03 \x01(\x04R\tbirthYear\x12\x14\n" +
	"\x05breed\x18\x04 \x01(\tR\x05breed\x12\x16\n" +
	"\x06specie\x18\x05 \x01(\x04R\x06specie\"\xd8\x01\n" +
	"\x11CreatePetResponse\x12)\n" +
	"\x10n_identification\x18\x01 \x01(\x03R\x0fnIdentification\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12#\n" +
	"\ruuid_guardian\x18\x03 \x01(\tR\fuuidGuardian\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"birth_year\x18\x05 \x01(\x04R\tbirthYear\x12\x14\n" +
	"\x05breed\x18\x06 \x01(\tR\x05breed\x12\x16\n" +
	"\x06specie\x18\a \x01(\tR\x06specie\"\x87\x01\n" +
	"\x10UpdatePetRequest\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"birth_year\x18\x05 \x01(\x04R\tbirthYear\x12\x14\n" +
	"\x05breed\x18\x06 \x01(\tR\x05breed\x12\x16\n" +
	"\x06specie\x18\a \x01(\x04R\x06specie\"\xd8\x01\n" +
	"\x11UpdatePetResponse\x12)\n" +
	"\x10n_identification\x18\x01 \x01(\x03R\x0fnIdentification\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12#\n" +
	"\ruuid_guardian\x18\x03 \x01(\tR\fuuidGuardian\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"birth_year\x18\x05 \x01(\x04R\tbirthYear\x12\x14\n" +
	"\x05breed\x18\x06 \x01(\tR\x05breed\x12\x16\n" +
	"\x06specie\x18\a \x01(\tR\x06specie\"7\n" +
	"\x10DeletePetRequest\x12#\n" +
	"\ruuid_guardian\x18\x01 \x01(\tR\fuuidGuardian\"-\n" +
	"\x11DeletePetResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"#\n" +
	"\rGetPetRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\xd5\x01\n" +
	"\x0eGetPetResponse\x12)\n" +
	"\x10n_identification\x18\x01 \x01(\x03R\x0fnIdentification\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12#\n" +
	"\ruuid_guardian\x18\x03 \x01(\tR\fuuidGuardian\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"birth_year\x18\x05 \x01(\x04R\tbirthYear\x12\x14\n" +
	"\x05breed\x18\x06 \x01(\tR\x05breed\x12\x16\n" +
	"\x06specie\x18\a \x01(\tR\x06specie2\xd7\x02\n" +
	"\n" +
	"PetService\x12M\n" +
	"\x06Create\x12\x17.proto.CreatePetRequest\x1a\x18.proto.CreatePetResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	":\x01*\"\x05/pets\x12T\n" +
	"\x06Update\x12\x17.proto.UpdatePetRequest\x1a\x18.proto.UpdatePetResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\x1a\f/pets/{uuid}\x12Z\n" +
	"\x06Delete\x12\x17.proto.DeletePetRequest\x1a\x18.proto.DeletePetResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/pets/{uuid_guardian}\x12H\n" +
	"\x03Get\x12\x14.proto.GetPetRequest\x1a\x15.proto.GetPetResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/pets/{uuid}B#Z!https://github.com/LuizFJP/pet-msb\x06proto3"

var (
	file_pet_ms_proto_rawDescOnce sync.Once
	file_pet_ms_proto_rawDescData []byte
)

func file_pet_ms_proto_rawDescGZIP() []byte {
	file_pet_ms_proto_rawDescOnce.Do(func() {
		file_pet_ms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pet_ms_proto_rawDesc), len(file_pet_ms_proto_rawDesc)))
	})
	return file_pet_ms_proto_rawDescData
}

var file_pet_ms_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pet_ms_proto_goTypes = []any{
	(*CreatePetRequest)(nil),  // 0: proto.CreatePetRequest
	(*CreatePetResponse)(nil), // 1: proto.CreatePetResponse
	(*UpdatePetRequest)(nil),  // 2: proto.UpdatePetRequest
	(*UpdatePetResponse)(nil), // 3: proto.UpdatePetResponse
	(*DeletePetRequest)(nil),  // 4: proto.DeletePetRequest
	(*DeletePetResponse)(nil), // 5: proto.DeletePetResponse
	(*GetPetRequest)(nil),     // 6: proto.GetPetRequest
	(*GetPetResponse)(nil),    // 7: proto.GetPetResponse
}
var file_pet_ms_proto_depIdxs = []int32{
	0, // 0: proto.PetService.Create:input_type -> proto.CreatePetRequest
	2, // 1: proto.PetService.Update:input_type -> proto.UpdatePetRequest
	4, // 2: proto.PetService.Delete:input_type -> proto.DeletePetRequest
	6, // 3: proto.PetService.Get:input_type -> proto.GetPetRequest
	1, // 4: proto.PetService.Create:output_type -> proto.CreatePetResponse
	3, // 5: proto.PetService.Update:output_type -> proto.UpdatePetResponse
	5, // 6: proto.PetService.Delete:output_type -> proto.DeletePetResponse
	7, // 7: proto.PetService.Get:output_type -> proto.GetPetResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pet_ms_proto_init() }
func file_pet_ms_proto_init() {
	if File_pet_ms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pet_ms_proto_rawDesc), len(file_pet_ms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pet_ms_proto_goTypes,
		DependencyIndexes: file_pet_ms_proto_depIdxs,
		MessageInfos:      file_pet_ms_proto_msgTypes,
	}.Build()
	File_pet_ms_proto = out.File
	file_pet_ms_proto_goTypes = nil
	file_pet_ms_proto_depIdxs = nil
}
